Language:java
sudo:false
jobs:
  include:
    -stage: Tests
     script: echo "`data` Unit Tests1" && sleep 1
     name: "Unit Tests"
    -script:echo "`data` Integration-tests" && sleep 2
     name: "Intergration Tests"
    -stage: build
     name: "Mvn build"
     script: mvn package
deploy:
  provider: releases
  api_key: "$API_KEY"
  file: "target/my-app-1.8-SNAPSHOT.jar"
  skip_cleanup: true